### ISSUE TITLE
gopls: automated issue report (initialization)

### ISSUE THREAD

**Issue by aryoprakarsa** [golang/vscode-go#1049]
gopls version: v0.6.1
gopls flags: 

ATTENTION: PLEASE PROVIDE THE DETAILS REQUESTED BELOW.

Describe what you observed.

<ANSWER HERE>

<pre>Starting client failed
  Message: unsupported URI schemes: [{vsls:/ neptune}] (gopls only supports file URIs)
  Code: 0 </pre>

OPTIONAL: If you would like to share more information, you can attach your complete gopls logs.

NOTE: THESE MAY CONTAIN SENSITIVE INFORMATION ABOUT YOUR CODEBASE.
DO NOT SHARE LOGS IF YOU ARE WORKING IN A PRIVATE REPOSITORY.

<OPTIONAL: ATTACH LOGS HERE>

**Comment by stamblerre** [comment]
Are you using the latest version of the VS Code Go extension? Please update if not. I believe this crash should be fixed with 0.19.1.

**Comment by hyangah** [comment]
v0.20.0 is released. @aryoprakarsa please open a new issue the crash still occurs after update. Thanks!

**Comment by aryoprakarsa** [comment]
Yeah it is being solved after updated the go version manually.
