### ISSUE TITLE
debug: error message when debug run withoun launch.json

### ISSUE THREAD

**Issue by aleksandr-shevchenko** [golang/vscode-go#1113]
a.go:
package main
import "fmt"
func main() {
    fmt.Println(2 + 3)
}

1. run "code a.go" or "code ."  and open a.go
2. press F5
3. in 99% vscode write

API server listening at: 127.0.0.1:27232
5
Failed to get state - Process 11708 has exited with status 0
dumpStacktrace - Failed to get debugger state Process 11708 has exited with status 0
dumpStacktrace: Failed to produce stack traceProcess 11708 has exited with status 0
Process exiting with code: 0

4. when create standard launch.json(launch file) and press F5, in 100% cases no any error messages

VSCode and golang latest version, but this behavior I see last half year.

My custom settings
  "go.formatTool": "goimports",
  "go.useLanguageServer": true,
  "go.buildOnSave": "off",
  "go.lintOnSave": "file",
  "go.docsTool": "gogetdoc",

  "[go]": {
    "editor.detectIndentation": false,
    "editor.tabSize": 4,
    "editor.insertSpaces": true,
    "editor.formatOnSave": false,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    },
    "editor.snippetSuggestions": "none"
  },

  "[go.mod]": {
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
      "source.organizeImports": true
    }
  },

  "gopls": {
    "usePlaceholders": true
  },

**Comment by suzmue** [comment]
Thanks for filing an issue! It seems these two configurations happen to hit the timing of events differently. The terminated event is sent before the initial ThreadsRequest from vscode, causing an error when trying to get the debug state.

```
[19:53:35.408 UTC] To client: {"seq":0,"type":"event","event":"terminated"}
[19:53:35.408 UTC] TerminatedEvent
[19:53:35.440 UTC] From client: threads(undefined)
[19:53:35.441 UTC] [Error] Failed to get state - Process 31728 has exited with status 0
[19:53:35.441 UTC] ThreadsRequest
[19:53:35.441 UTC] [Error] dumpStacktrace - Failed to get debugger state Process 31728 has exited with status 0
[19:53:35.442 UTC] To client: {"seq":0,"type":"response","request_seq":4,"command":"threads","success":true,"body":{"threads":[]}}
[19:53:35.442 UTC] [Error] dumpStacktrace: Failed to produce stack traceProcess 31728 has exited with status 0
```

We can guard against requests sent after delve has exited to fix this.

**Comment by hyangah** [comment]
@suzmue Is this fixed by cl/286492? Can we close this?

**Comment by aleksandr-shevchenko** [comment]
No, not fixed.
![ss_2021_03_02__10_24_56](https://user-images.githubusercontent.com/25248634/109607443-a407d700-7b41-11eb-95f3-9f9d9710c1d8.png)

**Comment by suzmue** [comment]
@aleksandr-shevchenko The fix has not yet been released (it will be released in 0.23.0).

Could you try to install and use 'Go Nightly' to confirm that the error still appears? Thank you!

**Comment by aleksandr-shevchenko** [comment]
Suzi, 'Go Nightly' works without error. Thank you very much.

**Comment by suzmue** [comment]
@aleksandr-shevchenko Thanks for trying it out and letting us know! Will close this issue :)

**Comment by IvanTurgenev** [comment]
I am getting this same error when I placed a breakpoint in an empty line, could not figure out why it was crashing

**Comment by suzmue** [comment]
@IvanTurgenev could you please file a new issue with the debugging logs so we can look into what is happening? Instructions for capturing logs can be found [here](https://github.com/golang/vscode-go/issues/1729).
