### ISSUE TITLE
Resolved import cycles are not cleared from "PROBLEMS" tab

### ISSUE THREAD

**Issue by jmaister** [golang/vscode-go#1653]
Issue Type: <b>Bug</b>

1. Create 3 go modules, A, B, C
2. Import B from A, then import C from B, finally import A from C
3. The PROBLEMS tab keeps showing that there are erros with the imports

Extension version: 0.26.0
VS Code version: Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3, 2021-07-14T22:10:15.214Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by hyangah** [comment]
@jmaister Can you please share more details to help triage? Thanks!

- go version, gopls version
- vscode settings - anything that starts with `"go"` or `"gopls"`
- module-level cycle is fine, but package-level import cycle is an error that needs fix.
- If the error keeps showing after you fix the problem by removing the import cycle, can you share the gopls trace following this ["collect gopls information" instruction](https://github.com/golang/vscode-go/blob/master/docs/troubleshooting.md#collect-gopls-information)?

**Comment by jmaister** [comment]
go version: go version go1.16.5 windows/amd64
gopls version:
```
Build info
----------
golang.org/x/tools/gopls v0.7.0
    golang.org/x/tools/gopls@v0.7.0 h1:JQBHW81Gsyim6iDjUwGoPeSpXrSqwen3isPJLfDfaYU=
    github.com/BurntSushi/toml@v0.3.1 h1:WXkYYl6Yr3qBf1K79EBnL4mak0OimBfB0XUf9Vl28OQ=
    github.com/google/go-cmp@v0.5.5 h1:Khx7svrCpmxxtHBq5j2mp/xVjsi8hQMfNLvJFAlrGgU=
    github.com/sergi/go-diff@v1.1.0 h1:we8PVUC3FE2uYfodKH/nBHMSetSfHDR6scGdBi+erh0=
    golang.org/x/mod@v0.4.2 h1:Gz96sIWK3OalVv/I/qNygP42zyoKp3xptRVCWRFEBvo=
    golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c h1:5KslGYwFpkhGh+Q16bwMP3cOontH8FOep7tGV86Y7SQ=
    golang.org/x/sys@v0.0.0-20210510120138-977fb7262007 h1:gG67DSER+11cZvqIMb8S8bt0vZtiN6xWYARwirrOSfE=
    golang.org/x/tools@v0.1.3-0.20210608163600-9ed039809d4c h1:Pv9gNyJFYVdpUAVZYJ1BDSU4eGgXQ+0f3DIGAdolO5s=
    golang.org/x/xerrors@v0.0.0-20200804184101-5ec99f83aff1 h1:go1bK/D/BFZV2I8cIQd1NKEZ+0owSTG1fDTci4IqFcE=
    honnef.co/go/tools@v0.2.0 h1:ws8AfbgTX3oIczLPNPCu5166oBg9ST2vNs0rcht+mDE=
    mvdan.cc/gofumpt@v0.1.1 h1:bi/1aS/5W00E2ny5q65w9SnKpWEF/UIOqDYBILpo9rA=
    mvdan.cc/xurls/v2@v2.2.0 h1:NSZPykBXJFCetGZykLAxaL6SIpvbVy/UFEniIfHAa8A=
```
vscode settings: 
```json
{
    "files.eol": "\n",
}
```

And here is the trace of gopls (server) after removing the lines that create the cycle.

```
[Trace - 00:11:49.302 AM] Sending request 'textDocument/codeAction - (94)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"},"range":{"start":{"line":355,"character":67},"end":{"line":355,"character":67}},"context":{"diagnostics":[]}}


[Trace - 00:11:49.303 AM] Received response 'textDocument/codeAction - (94)' in 1ms.
Result: null


[Trace - 00:11:50.076 AM] Sending request 'textDocument/codeLens - (95)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"}}


[Trace - 00:11:50.076 AM] Received response 'textDocument/codeLens - (95)' in 0ms.
Result: null


[Trace - 00:11:51.207 AM] Sending request 'textDocument/documentHighlight - (96)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"},"position":{"line":355,"character":0}}


[Trace - 00:11:51.208 AM] Received response 'textDocument/documentHighlight - (96)' in 0ms.
Result: [{"range":{"start":{"line":355,"character":0},"end":{"line":355,"character":4}},"kind":1},{"range":{"start":{"line":356,"character":1},"end":{"line":356,"character":17}},"kind":1}]


[Trace - 00:11:51.461 AM] Sending request 'textDocument/codeAction - (97)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"},"range":{"start":{"line":355,"character":0},"end":{"line":355,"character":0}},"context":{"diagnostics":[]}}


[Trace - 00:11:51.463 AM] Received response 'textDocument/codeAction - (97)' in 1ms.
Result: null


[Trace - 00:11:52.270 AM] Sending request 'textDocument/codeAction - (98)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"},"range":{"start":{"line":355,"character":0},"end":{"line":358,"character":0}},"context":{"diagnostics":[]}}


[Trace - 00:11:52.272 AM] Received response 'textDocument/codeAction - (98)' in 1ms.
Result: null


[Trace - 00:11:52.801 AM] Sending notification 'textDocument/didChange'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go","version":32},"contentChanges":[{"range":{"start":{"line":355,"character":0},"end":{"line":358,"character":0}},"rangeLength":88,"text":""}]}


[Trace - 00:11:52.817 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///C:/workspace/officestruggle/state/components.go","version":32,"diagnostics":[{"range":{"start":{"line":7,"character":1},"end":{"line":7,"character":43}},"severity":1,"code":"UnusedImport","codeDescription":{"href":"https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source=gopls#UnusedImport"},"source":"compiler","message":"\"jordiburgos.com/officestruggle/gamestate\" imported but not used"},{"range":{"start":{"line":7,"character":1},"end":{"line":7,"character":43}},"severity":1,"source":"compiler","message":"import cycle not allowed"}]}


[Trace - 00:11:52.983 AM] Sending request 'textDocument/foldingRange - (99)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"}}


[Trace - 00:11:52.984 AM] Received response 'textDocument/foldingRange - (99)' in 1ms.
Result: [{"startLine":2,"startCharacter":8,"endLine":7,"endCharacter":43,"kind":"imports"},{"startLine":10,"startCharacter":7,"endLine":31,"endCharacter":25},{"startLine":37,"startCharacter":49,"endLine":38,"endCharacter":14},{"startLine":41,"startCharacter":32,"endLine":44,"endCharacter":11},{"startLine":47,"startCharacter":52,"endLine":48,"endCharacter":17},{"startLine":51,"startCharacter":31,"endLine":53,"endCharacter":6},{"startLine":56,"startCharacter":51,"endLine":57,"endCharacter":16},{"startLine":60,"startCharacter":56,"endLine":61,"endCharacter":57},{"startLine":64,"startCharacter":44,"endLine":65,"endCharacter":51},{"startLine":68,"startCharacter":44,"endLine":69,"endCharacter":18},{"startLine":72,"startCharacter":74,"endLine":73,"endCharacter":40},{"startLine":76,"startCharacter":77,"endLine":77,"endCharacter":43},{"startLine":80,"startCharacter":27,"endLine":82,"endCharacter":6},{"startLine":85,"startCharacter":47,"endLine":86,"endCharacter":12},{"startLine":91,"startCharacter":53,"endLine":92,"endCharacter":18},{"startLine":97,"startCharacter":50,"endLine":98,"endCharacter":15},{"startLine":103,"startCharacter":51,"endLine":104,"endCharacter":16},{"startLine":109,"startCharacter":51,"endLine":110,"endCharacter":16},{"startLine":115,"startCharacter":51,"endLine":116,"endCharacter":16},{"startLine":121,"startCharacter":51,"endLine":122,"endCharacter":16},{"startLine":125,"startCharacter":32,"endLine":129,"endCharacter":13},{"startLine":132,"startCharacter":52,"endLine":133,"endCharacter":17},{"startLine":136,"startCharacter":34,"endLine":137,"endCharacter":12},{"startLine":140,"startCharacter":54,"endLine":141,"endCharacter":19},{"startLine":144,"startCharacter":48,"endLine":149,"endCharacter":20},{"startLine":146,"startCharacter":8,"endLine":147,"endCharacter":17},{"startLine":152,"startCharacter":52,"endLine":173,"endCharacter":20},{"startLine":154,"startCharacter":8,"endLine":171,"endCharacter":12},{"startLine":157,"startCharacter":32,"endLine":158,"endCharacter":24},{"startLine":161,"startCharacter":33,"endLine":163,"endCharacter":42},{"startLine":164,"startCharacter":45,"endLine":166,"endCharacter":41},{"startLine":167,"startCharacter":44,"endLine":169,"endCharacter":39},{"startLine":179,"startCharacter":45,"endLine":180,"endCharacter":10},{"startLine":183,"startCharacter":25,"endLine":191,"endCharacter":15},{"startLine":194,"startCharacter":38,"endLine":200,"endCharacter":28},{"startLine":203,"startCharacter":65,"endLine":215,"endCharacter":15},{"startLine":218,"startCharacter":51,"endLine":223,"endCharacter":15},{"startLine":220,"startCharacter":19,"endLine":221,"endCharacter":12},{"startLine":226,"startCharacter":28,"endLine":230,"endCharacter":23},{"startLine":227,"startCharacter":12,"endLine":228,"endCharacter":30},{"startLine":233,"startCharacter":55,"endLine":237,"endCharacter":10},{"startLine":234,"startCharacter":28,"endLine":235,"endCharacter":63},{"startLine":240,"startCharacter":28,"endLine":241,"endCharacter":13},{"startLine":244,"startCharacter":48,"endLine":245,"endCharacter":13},{"startLine":248,"startCharacter":33,"endLine":249,"endCharacter":13},{"startLine":252,"startCharacter":53,"endLine":253,"endCharacter":18},{"startLine":259,"startCharacter":51,"endLine":260,"endCharacter":16},{"startLine":266,"startCharacter":47,"endLine":267,"endCharacter":12},{"startLine":270,"startCharacter":32,"endLine":272,"endCharacter":13},{"startLine":275,"startCharacter":63,"endLine":280,"endCharacter":12},{"startLine":276,"startCharacter":32,"endLine":277,"endCharacter":14},{"startLine":283,"startCharacter":66,"endLine":290,"endCharacter":13},{"startLine":284,"startCharacter":31,"endLine":288,"endCharacter":3},{"startLine":285,"startCharacter":21,"endLine":287,"endCharacter":14},{"startLine":293,"startCharacter":52,"endLine":294,"endCharacter":17},{"startLine":297,"startCharacter":32,"endLine":300,"endCharacter":24},{"startLine":303,"startCharacter":52,"endLine":304,"endCharacter":17},{"startLine":309,"startCharacter":7,"endLine":314,"endCharacter":36},{"startLine":317,"startCharacter":41,"endLine":322,"endCharacter":11},{"startLine":325,"startCharacter":32,"endLine":327,"endCharacter":36},{"startLine":330,"startCharacter":62,"endLine":338,"endCharacter":3},{"startLine":332,"startCharacter":31,"endLine":334,"endCharacter":51},{"startLine":336,"startCharacter":25,"endLine":338,"endCharacter":2},{"startLine":336,"startCharacter":47,"endLine":337,"endCharacter":24},{"startLine":341,"startCharacter":75,"endLine":343,"endCharacter":22},{"startLine":346,"startCharacter":78,"endLine":348,"endCharacter":22},{"startLine":351,"startCharacter":52,"endLine":352,"endCharacter":17}]


[Trace - 00:11:53.574 AM] Sending request 'textDocument/codeAction - (100)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"},"range":{"start":{"line":0,"character":0},"end":{"line":355,"character":0}},"context":{"diagnostics":[{"range":{"start":{"line":7,"character":1},"end":{"line":7,"character":43}},"message":"\"jordiburgos.com/officestruggle/gamestate\" imported but not used","code":"UnusedImport","codeDescription":{"href":"https://pkg.go.dev/golang.org/x/tools/internal/typesinternal?utm_source%3Dgopls#UnusedImport"},"severity":1,"source":"compiler"},{"range":{"start":{"line":7,"character":1},"end":{"line":7,"character":43}},"message":"import cycle not allowed","severity":1,"source":"compiler"}],"only":["source.organizeImports"]}}


[Trace - 00:11:53.576 AM] Received response 'textDocument/codeAction - (100)' in 2ms.
Result: [{"title":"Organize Imports","kind":"source.organizeImports","edit":{"documentChanges":[{"textDocument":{"version":32,"uri":"file:///C:/workspace/officestruggle/state/components.go"},"edits":[{"range":{"start":{"line":7,"character":0},"end":{"line":8,"character":0}},"newText":""}]}]}}]


[Trace - 00:11:53.587 AM] Sending notification 'textDocument/didChange'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go","version":33},"contentChanges":[{"range":{"start":{"line":7,"character":0},"end":{"line":8,"character":0}},"rangeLength":44,"text":""}]}


[Trace - 00:11:53.587 AM] Sending request 'textDocument/formatting - (101)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"},"options":{"tabSize":4,"insertSpaces":false}}


[Trace - 00:11:53.600 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///C:/workspace/officestruggle/state/components.go","version":33,"diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"go list","message":"import cycle not allowed: import stack: [jordiburgos.com/officestruggle/state jordiburgos.com/officestruggle/gamestate jordiburgos.com/officestruggle/dungeon jordiburgos.com/officestruggle/state]"}]}


[Trace - 00:11:53.600 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {"uri":"file:///C:/workspace/officestruggle/state/entities.go","diagnostics":[{"range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}},"severity":1,"source":"go list","message":"import cycle not allowed: import stack: [jordiburgos.com/officestruggle/state jordiburgos.com/officestruggle/gamestate jordiburgos.com/officestruggle/dungeon jordiburgos.com/officestruggle/state]"}]}


[Trace - 00:11:53.602 AM] Received response 'textDocument/formatting - (101)' in 15ms.
Result: [{"range":{"start":{"line":353,"character":0},"end":{"line":354,"character":0}},"newText":""}]


[Trace - 00:11:53.666 AM] Sending notification 'textDocument/didChange'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go","version":34},"contentChanges":[{"range":{"start":{"line":353,"character":0},"end":{"line":354,"character":0}},"rangeLength":1,"text":""}]}


[Trace - 00:11:53.701 AM] Sending notification 'textDocument/didSave'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"}}


[Trace - 00:11:53.782 AM] Sending request 'textDocument/documentLink - (102)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"}}


[Trace - 00:11:53.784 AM] Received response 'textDocument/documentLink - (102)' in 2ms.
Result: [{"range":{"start":{"line":3,"character":2},"end":{"line":3,"character":9}},"target":"https://pkg.go.dev/strconv?utm_source=gopls"},{"range":{"start":{"line":4,"character":2},"end":{"line":4,"character":9}},"target":"https://pkg.go.dev/strings?utm_source=gopls"},{"range":{"start":{"line":6,"character":2},"end":{"line":6,"character":36}},"target":"https://pkg.go.dev/jordiburgos.com/officestruggle/ecs?utm_source=gopls"}]


[Trace - 00:11:53.847 AM] Sending request 'textDocument/foldingRange - (103)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"}}


[Trace - 00:11:53.850 AM] Received response 'textDocument/foldingRange - (103)' in 2ms.
Result: [{"startLine":2,"startCharacter":8,"endLine":6,"endCharacter":37,"kind":"imports"},{"startLine":9,"startCharacter":7,"endLine":30,"endCharacter":25},{"startLine":36,"startCharacter":49,"endLine":37,"endCharacter":14},{"startLine":40,"startCharacter":32,"endLine":43,"endCharacter":11},{"startLine":46,"startCharacter":52,"endLine":47,"endCharacter":17},{"startLine":50,"startCharacter":31,"endLine":52,"endCharacter":6},{"startLine":55,"startCharacter":51,"endLine":56,"endCharacter":16},{"startLine":59,"startCharacter":56,"endLine":60,"endCharacter":57},{"startLine":63,"startCharacter":44,"endLine":64,"endCharacter":51},{"startLine":67,"startCharacter":44,"endLine":68,"endCharacter":18},{"startLine":71,"startCharacter":74,"endLine":72,"endCharacter":40},{"startLine":75,"startCharacter":77,"endLine":76,"endCharacter":43},{"startLine":79,"startCharacter":27,"endLine":81,"endCharacter":6},{"startLine":84,"startCharacter":47,"endLine":85,"endCharacter":12},{"startLine":90,"startCharacter":53,"endLine":91,"endCharacter":18},{"startLine":96,"startCharacter":50,"endLine":97,"endCharacter":15},{"startLine":102,"startCharacter":51,"endLine":103,"endCharacter":16},{"startLine":108,"startCharacter":51,"endLine":109,"endCharacter":16},{"startLine":114,"startCharacter":51,"endLine":115,"endCharacter":16},{"startLine":120,"startCharacter":51,"endLine":121,"endCharacter":16},{"startLine":124,"startCharacter":32,"endLine":128,"endCharacter":13},{"startLine":131,"startCharacter":52,"endLine":132,"endCharacter":17},{"startLine":135,"startCharacter":34,"endLine":136,"endCharacter":12},{"startLine":139,"startCharacter":54,"endLine":140,"endCharacter":19},{"startLine":143,"startCharacter":48,"endLine":148,"endCharacter":20},{"startLine":145,"startCharacter":8,"endLine":146,"endCharacter":17},{"startLine":151,"startCharacter":52,"endLine":172,"endCharacter":20},{"startLine":153,"startCharacter":8,"endLine":170,"endCharacter":12},{"startLine":156,"startCharacter":32,"endLine":157,"endCharacter":24},{"startLine":160,"startCharacter":33,"endLine":162,"endCharacter":42},{"startLine":163,"startCharacter":45,"endLine":165,"endCharacter":41},{"startLine":166,"startCharacter":44,"endLine":168,"endCharacter":39},{"startLine":178,"startCharacter":45,"endLine":179,"endCharacter":10},{"startLine":182,"startCharacter":25,"endLine":190,"endCharacter":15},{"startLine":193,"startCharacter":38,"endLine":199,"endCharacter":28},{"startLine":202,"startCharacter":65,"endLine":214,"endCharacter":15},{"startLine":217,"startCharacter":51,"endLine":222,"endCharacter":15},{"startLine":219,"startCharacter":19,"endLine":220,"endCharacter":12},{"startLine":225,"startCharacter":28,"endLine":229,"endCharacter":23},{"startLine":226,"startCharacter":12,"endLine":227,"endCharacter":30},{"startLine":232,"startCharacter":55,"endLine":236,"endCharacter":10},{"startLine":233,"startCharacter":28,"endLine":234,"endCharacter":63},{"startLine":239,"startCharacter":28,"endLine":240,"endCharacter":13},{"startLine":243,"startCharacter":48,"endLine":244,"endCharacter":13},{"startLine":247,"startCharacter":33,"endLine":248,"endCharacter":13},{"startLine":251,"startCharacter":53,"endLine":252,"endCharacter":18},{"startLine":258,"startCharacter":51,"endLine":259,"endCharacter":16},{"startLine":265,"startCharacter":47,"endLine":266,"endCharacter":12},{"startLine":269,"startCharacter":32,"endLine":271,"endCharacter":13},{"startLine":274,"startCharacter":63,"endLine":279,"endCharacter":12},{"startLine":275,"startCharacter":32,"endLine":276,"endCharacter":14},{"startLine":282,"startCharacter":66,"endLine":289,"endCharacter":13},{"startLine":283,"startCharacter":31,"endLine":287,"endCharacter":3},{"startLine":284,"startCharacter":21,"endLine":286,"endCharacter":14},{"startLine":292,"startCharacter":52,"endLine":293,"endCharacter":17},{"startLine":296,"startCharacter":32,"endLine":299,"endCharacter":24},{"startLine":302,"startCharacter":52,"endLine":303,"endCharacter":17},{"startLine":308,"startCharacter":7,"endLine":313,"endCharacter":36},{"startLine":316,"startCharacter":41,"endLine":321,"endCharacter":11},{"startLine":324,"startCharacter":32,"endLine":326,"endCharacter":36},{"startLine":329,"startCharacter":62,"endLine":337,"endCharacter":3},{"startLine":331,"startCharacter":31,"endLine":333,"endCharacter":51},{"startLine":335,"startCharacter":25,"endLine":337,"endCharacter":2},{"startLine":335,"startCharacter":47,"endLine":336,"endCharacter":24},{"startLine":340,"startCharacter":75,"endLine":342,"endCharacter":22},{"startLine":345,"startCharacter":78,"endLine":347,"endCharacter":22},{"startLine":350,"startCharacter":52,"endLine":351,"endCharacter":17}]


[Trace - 00:11:54.084 AM] Sending notification 'workspace/didChangeWatchedFiles'.
Params: {"changes":[{"uri":"file:///c%3A/workspace/officestruggle/state/components.go","type":2}]}


[Trace - 00:11:54.516 AM] Sending request 'textDocument/codeLens - (104)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"}}


[Trace - 00:11:54.517 AM] Received response 'textDocument/codeLens - (104)' in 1ms.
Result: null


[Trace - 00:11:55.239 AM] Sending request 'textDocument/documentSymbol - (105)'.
Params: {"textDocument":{"uri":"file:///c%3A/workspace/officestruggle/state/components.go"}}


[Trace - 00:11:55.241 AM] Received response 'textDocument/documentSymbol - (105)' in 2ms.
Result: [{"name":"Player","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":10,"character":1},"end":{"line":10,"character":7}}},{"name":"Apparence","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":11,"character":1},"end":{"line":11,"character":10}}},{"name":"Position","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":12,"character":1},"end":{"line":12,"character":9}}},{"name":"Move","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":13,"character":1},"end":{"line":13,"character":5}}},{"name":"IsBlocking","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":14,"character":1},"end":{"line":14,"character":11}}},{"name":"IsFloor","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":15,"character":1},"end":{"line":15,"character":8}}},{"name":"Layer100","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":16,"character":1},"end":{"line":16,"character":9}}},{"name":"Layer300","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":17,"character":1},"end":{"line":17,"character":9}}},{"name":"Layer400","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":18,"character":1},"end":{"line":18,"character":9}}},{"name":"Layer500","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":19,"character":1},"end":{"line":19,"character":9}}},{"name":"Visitable","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":20,"character":1},"end":{"line":20,"character":10}}},{"name":"Description","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":21,"character":1},"end":{"line":21,"character":12}}},{"name":"AI","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":22,"character":1},"end":{"line":22,"character":3}}},{"name":"Stats","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":23,"character":1},"end":{"line":23,"character":6}}},{"name":"Consumable","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":24,"character":1},"end":{"line":24,"character":11}}},{"name":"IsPickup","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":25,"character":1},"end":{"line":25,"character":9}}},{"name":"Dead","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":26,"character":1},"end":{"line":26,"character":5}}},{"name":"Inventory","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":27,"character":1},"end":{"line":27,"character":10}}},{"name":"Equipable","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":28,"character":1},"end":{"line":28,"character":10}}},{"name":"Equipment","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":29,"character":1},"end":{"line":29,"character":10}}},{"name":"Animated","detail":"untyped string","kind":14,"range":{"start":{"line":9,"character":0},"end":{"line":31,"character":1}},"selectionRange":{"start":{"line":30,"character":1},"end":{"line":30,"character":9}}},{"name":"PlayerComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":33,"character":5},"end":{"line":34,"character":1}},"selectionRange":{"start":{"line":33,"character":5},"end":{"line":33,"character":20}}},{"name":"(PlayerComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":36,"character":0},"end":{"line":38,"character":1}},"selectionRange":{"start":{"line":36,"character":25},"end":{"line":36,"character":38}}},{"name":"ApparenceComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":40,"character":5},"end":{"line":44,"character":1}},"selectionRange":{"start":{"line":40,"character":5},"end":{"line":40,"character":23}},"children":[{"name":"Color","detail":"string","kind":8,"range":{"start":{"line":41,"character":1},"end":{"line":41,"character":13}},"selectionRange":{"start":{"line":41,"character":1},"end":{"line":41,"character":6}}},{"name":"Bg","detail":"string","kind":8,"range":{"start":{"line":42,"character":1},"end":{"line":42,"character":13}},"selectionRange":{"start":{"line":42,"character":1},"end":{"line":42,"character":3}}},{"name":"Char","detail":"rune","kind":8,"range":{"start":{"line":43,"character":1},"end":{"line":43,"character":11}},"selectionRange":{"start":{"line":43,"character":1},"end":{"line":43,"character":5}}}]},{"name":"(ApparenceComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":46,"character":0},"end":{"line":48,"character":1}},"selectionRange":{"start":{"line":46,"character":28},"end":{"line":46,"character":41}}},{"name":"PositionComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":50,"character":5},"end":{"line":53,"character":1}},"selectionRange":{"start":{"line":50,"character":5},"end":{"line":50,"character":22}},"children":[{"name":"X","detail":"int","kind":8,"range":{"start":{"line":51,"character":1},"end":{"line":51,"character":6}},"selectionRange":{"start":{"line":51,"character":1},"end":{"line":51,"character":2}}},{"name":"Y","detail":"int","kind":8,"range":{"start":{"line":52,"character":1},"end":{"line":52,"character":6}},"selectionRange":{"start":{"line":52,"character":1},"end":{"line":52,"character":2}}}]},{"name":"(PositionComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":55,"character":0},"end":{"line":57,"character":1}},"selectionRange":{"start":{"line":55,"character":27},"end":{"line":55,"character":40}}},{"name":"GetPosition","detail":"(entity *ecs.Entity)","kind":12,"range":{"start":{"line":59,"character":0},"end":{"line":61,"character":1}},"selectionRange":{"start":{"line":59,"character":5},"end":{"line":59,"character":16}}},{"name":"(PositionComponent).GetKey","detail":"()","kind":6,"range":{"start":{"line":63,"character":0},"end":{"line":65,"character":1}},"selectionRange":{"start":{"line":63,"character":27},"end":{"line":63,"character":33}}},{"name":"(PositionComponent).String","detail":"()","kind":6,"range":{"start":{"line":67,"character":0},"end":{"line":69,"character":1}},"selectionRange":{"start":{"line":67,"character":27},"end":{"line":67,"character":33}}},{"name":"(PositionComponent).OnAdd","detail":"(engine *ecs.Engine, entity *ecs.Entity)","kind":6,"range":{"start":{"line":71,"character":0},"end":{"line":73,"character":1}},"selectionRange":{"start":{"line":71,"character":27},"end":{"line":71,"character":32}}},{"name":"(PositionComponent).OnRemove","detail":"(engine *ecs.Engine, entity *ecs.Entity)","kind":6,"range":{"start":{"line":75,"character":0},"end":{"line":77,"character":1}},"selectionRange":{"start":{"line":75,"character":27},"end":{"line":75,"character":35}}},{"name":"MoveComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":79,"character":5},"end":{"line":82,"character":1}},"selectionRange":{"start":{"line":79,"character":5},"end":{"line":79,"character":18}},"children":[{"name":"X","detail":"int","kind":8,"range":{"start":{"line":80,"character":1},"end":{"line":80,"character":6}},"selectionRange":{"start":{"line":80,"character":1},"end":{"line":80,"character":2}}},{"name":"Y","detail":"int","kind":8,"range":{"start":{"line":81,"character":1},"end":{"line":81,"character":6}},"selectionRange":{"start":{"line":81,"character":1},"end":{"line":81,"character":2}}}]},{"name":"(MoveComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":84,"character":0},"end":{"line":86,"character":1}},"selectionRange":{"start":{"line":84,"character":23},"end":{"line":84,"character":36}}},{"name":"IsBlockingComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":88,"character":5},"end":{"line":88,"character":33}},"selectionRange":{"start":{"line":88,"character":5},"end":{"line":88,"character":24}}},{"name":"(IsBlockingComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":90,"character":0},"end":{"line":92,"character":1}},"selectionRange":{"start":{"line":90,"character":29},"end":{"line":90,"character":42}}},{"name":"IsFloorComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":94,"character":5},"end":{"line":94,"character":30}},"selectionRange":{"start":{"line":94,"character":5},"end":{"line":94,"character":21}}},{"name":"(IsFloorComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":96,"character":0},"end":{"line":98,"character":1}},"selectionRange":{"start":{"line":96,"character":26},"end":{"line":96,"character":39}}},{"name":"Layer100Component","detail":"struct{...}","kind":23,"range":{"start":{"line":100,"character":5},"end":{"line":100,"character":31}},"selectionRange":{"start":{"line":100,"character":5},"end":{"line":100,"character":22}}},{"name":"(Layer100Component).ComponentType","detail":"()","kind":6,"range":{"start":{"line":102,"character":0},"end":{"line":104,"character":1}},"selectionRange":{"start":{"line":102,"character":27},"end":{"line":102,"character":40}}},{"name":"Layer300Component","detail":"struct{...}","kind":23,"range":{"start":{"line":106,"character":5},"end":{"line":106,"character":31}},"selectionRange":{"start":{"line":106,"character":5},"end":{"line":106,"character":22}}},{"name":"(Layer300Component).ComponentType","detail":"()","kind":6,"range":{"start":{"line":108,"character":0},"end":{"line":110,"character":1}},"selectionRange":{"start":{"line":108,"character":27},"end":{"line":108,"character":40}}},{"name":"Layer400Component","detail":"struct{...}","kind":23,"range":{"start":{"line":112,"character":5},"end":{"line":112,"character":31}},"selectionRange":{"start":{"line":112,"character":5},"end":{"line":112,"character":22}}},{"name":"(Layer400Component).ComponentType","detail":"()","kind":6,"range":{"start":{"line":114,"character":0},"end":{"line":116,"character":1}},"selectionRange":{"start":{"line":114,"character":27},"end":{"line":114,"character":40}}},{"name":"Layer500Component","detail":"struct{...}","kind":23,"range":{"start":{"line":118,"character":5},"end":{"line":118,"character":31}},"selectionRange":{"start":{"line":118,"character":5},"end":{"line":118,"character":22}}},{"name":"(Layer500Component).ComponentType","detail":"()","kind":6,"range":{"start":{"line":120,"character":0},"end":{"line":122,"character":1}},"selectionRange":{"start":{"line":120,"character":27},"end":{"line":120,"character":40}}},{"name":"VisitableComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":124,"character":5},"end":{"line":129,"character":1}},"selectionRange":{"start":{"line":124,"character":5},"end":{"line":124,"character":23}},"children":[{"name":"Explored","detail":"bool","kind":8,"range":{"start":{"line":126,"character":1},"end":{"line":126,"character":14}},"selectionRange":{"start":{"line":126,"character":1},"end":{"line":126,"character":9}}},{"name":"Visible","detail":"bool","kind":8,"range":{"start":{"line":128,"character":1},"end":{"line":128,"character":13}},"selectionRange":{"start":{"line":128,"character":1},"end":{"line":128,"character":8}}}]},{"name":"(VisitableComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":131,"character":0},"end":{"line":133,"character":1}},"selectionRange":{"start":{"line":131,"character":28},"end":{"line":131,"character":41}}},{"name":"DescriptionComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":135,"character":5},"end":{"line":137,"character":1}},"selectionRange":{"start":{"line":135,"character":5},"end":{"line":135,"character":25}},"children":[{"name":"Name","detail":"string","kind":8,"range":{"start":{"line":136,"character":1},"end":{"line":136,"character":12}},"selectionRange":{"start":{"line":136,"character":1},"end":{"line":136,"character":5}}}]},{"name":"(DescriptionComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":139,"character":0},"end":{"line":141,"character":1}},"selectionRange":{"start":{"line":139,"character":30},"end":{"line":139,"character":43}}},{"name":"GetDescription","detail":"(entity *ecs.Entity)","kind":12,"range":{"start":{"line":143,"character":0},"end":{"line":149,"character":1}},"selectionRange":{"start":{"line":143,"character":5},"end":{"line":143,"character":19}}},{"name":"GetLongDescription","detail":"(entity *ecs.Entity)","kind":12,"range":{"start":{"line":151,"character":0},"end":{"line":173,"character":1}},"selectionRange":{"start":{"line":151,"character":5},"end":{"line":151,"character":23}}},{"name":"AIComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":175,"character":5},"end":{"line":176,"character":1}},"selectionRange":{"start":{"line":175,"character":5},"end":{"line":175,"character":16}}},{"name":"(AIComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":178,"character":0},"end":{"line":180,"character":1}},"selectionRange":{"start":{"line":178,"character":21},"end":{"line":178,"character":34}}},{"name":"StatsValues","detail":"struct{...}","kind":23,"range":{"start":{"line":182,"character":5},"end":{"line":191,"character":1}},"selectionRange":{"start":{"line":182,"character":5},"end":{"line":182,"character":16}},"children":[{"name":"Health","detail":"int","kind":8,"range":{"start":{"line":183,"character":1},"end":{"line":183,"character":15}},"selectionRange":{"start":{"line":183,"character":1},"end":{"line":183,"character":7}}},{"name":"MaxHealth","detail":"int","kind":8,"range":{"start":{"line":184,"character":1},"end":{"line":184,"character":15}},"selectionRange":{"start":{"line":184,"character":1},"end":{"line":184,"character":10}}},{"name":"Defense","detail":"int","kind":8,"range":{"start":{"line":185,"character":1},"end":{"line":185,"character":15}},"selectionRange":{"start":{"line":185,"character":1},"end":{"line":185,"character":8}}},{"name":"MaxDefense","detail":"int","kind":8,"range":{"start":{"line":186,"character":1},"end":{"line":186,"character":15}},"selectionRange":{"start":{"line":186,"character":1},"end":{"line":186,"character":11}}},{"name":"Power","detail":"int","kind":8,"range":{"start":{"line":187,"character":1},"end":{"line":187,"character":15}},"selectionRange":{"start":{"line":187,"character":1},"end":{"line":187,"character":6}}},{"name":"MaxPower","detail":"int","kind":8,"range":{"start":{"line":188,"character":1},"end":{"line":188,"character":15}},"selectionRange":{"start":{"line":188,"character":1},"end":{"line":188,"character":9}}},{"name":"Fov","detail":"int","kind":8,"range":{"start":{"line":189,"character":1},"end":{"line":189,"character":15}},"selectionRange":{"start":{"line":189,"character":1},"end":{"line":189,"character":4}}},{"name":"MaxFov","detail":"int","kind":8,"range":{"start":{"line":190,"character":1},"end":{"line":190,"character":15}},"selectionRange":{"start":{"line":190,"character":1},"end":{"line":190,"character":7}}}]},{"name":"(StatsValues).String","detail":"()","kind":6,"range":{"start":{"line":193,"character":0},"end":{"line":200,"character":1}},"selectionRange":{"start":{"line":193,"character":21},"end":{"line":193,"character":27}}},{"name":"(StatsValues).Merge","detail":"(other StatsValues)","kind":6,"range":{"start":{"line":202,"character":0},"end":{"line":215,"character":1}},"selectionRange":{"start":{"line":202,"character":27},"end":{"line":202,"character":32}}},{"name":"increase","detail":"(current int, max int, incr int)","kind":12,"range":{"start":{"line":217,"character":0},"end":{"line":223,"character":1}},"selectionRange":{"start":{"line":217,"character":5},"end":{"line":217,"character":13}}},{"name":"addSign","detail":"(i int)","kind":12,"range":{"start":{"line":225,"character":0},"end":{"line":230,"character":1}},"selectionRange":{"start":{"line":225,"character":5},"end":{"line":225,"character":12}}},{"name":"statDiff","detail":"(name string, value int, max int)","kind":12,"range":{"start":{"line":232,"character":0},"end":{"line":237,"character":1}},"selectionRange":{"start":{"line":232,"character":5},"end":{"line":232,"character":13}}},{"name":"StatsComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":239,"character":5},"end":{"line":241,"character":1}},"selectionRange":{"start":{"line":239,"character":5},"end":{"line":239,"character":19}},"children":[{"name":"StatsValues","detail":"*StatsValues","kind":8,"range":{"start":{"line":240,"character":1},"end":{"line":240,"character":13}},"selectionRange":{"start":{"line":240,"character":1},"end":{"line":240,"character":13}}}]},{"name":"(StatsComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":243,"character":0},"end":{"line":245,"character":1}},"selectionRange":{"start":{"line":243,"character":24},"end":{"line":243,"character":37}}},{"name":"ConsumableComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":247,"character":5},"end":{"line":249,"character":1}},"selectionRange":{"start":{"line":247,"character":5},"end":{"line":247,"character":24}},"children":[{"name":"StatsValues","detail":"*StatsValues","kind":8,"range":{"start":{"line":248,"character":1},"end":{"line":248,"character":13}},"selectionRange":{"start":{"line":248,"character":1},"end":{"line":248,"character":13}}}]},{"name":"(ConsumableComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":251,"character":0},"end":{"line":253,"character":1}},"selectionRange":{"start":{"line":251,"character":29},"end":{"line":251,"character":42}}},{"name":"IsPickupComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":255,"character":5},"end":{"line":256,"character":1}},"selectionRange":{"start":{"line":255,"character":5},"end":{"line":255,"character":22}}},{"name":"(IsPickupComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":258,"character":0},"end":{"line":260,"character":1}},"selectionRange":{"start":{"line":258,"character":27},"end":{"line":258,"character":40}}},{"name":"DeadComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":262,"character":5},"end":{"line":263,"character":1}},"selectionRange":{"start":{"line":262,"character":5},"end":{"line":262,"character":18}}},{"name":"(DeadComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":265,"character":0},"end":{"line":267,"character":1}},"selectionRange":{"start":{"line":265,"character":23},"end":{"line":265,"character":36}}},{"name":"InventoryComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":269,"character":5},"end":{"line":272,"character":1}},"selectionRange":{"start":{"line":269,"character":5},"end":{"line":269,"character":23}},"children":[{"name":"Items","detail":"[]*ecs.Entity","kind":8,"range":{"start":{"line":270,"character":1},"end":{"line":270,"character":24}},"selectionRange":{"start":{"line":270,"character":1},"end":{"line":270,"character":6}}},{"name":"MaxItems","detail":"int","kind":8,"range":{"start":{"line":271,"character":1},"end":{"line":271,"character":13}},"selectionRange":{"start":{"line":271,"character":1},"end":{"line":271,"character":9}}}]},{"name":"(*InventoryComponent).AddItem","detail":"(entity *ecs.Entity)","kind":6,"range":{"start":{"line":274,"character":0},"end":{"line":280,"character":1}},"selectionRange":{"start":{"line":274,"character":29},"end":{"line":274,"character":36}}},{"name":"(*InventoryComponent).RemoveItem","detail":"(entity *ecs.Entity)","kind":6,"range":{"start":{"line":282,"character":0},"end":{"line":290,"character":1}},"selectionRange":{"start":{"line":282,"character":29},"end":{"line":282,"character":39}}},{"name":"(InventoryComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":292,"character":0},"end":{"line":294,"character":1}},"selectionRange":{"start":{"line":292,"character":28},"end":{"line":292,"character":41}}},{"name":"EquipableComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":296,"character":5},"end":{"line":300,"character":1}},"selectionRange":{"start":{"line":296,"character":5},"end":{"line":296,"character":23}},"children":[{"name":"StatsValues","detail":"*StatsValues","kind":8,"range":{"start":{"line":297,"character":1},"end":{"line":297,"character":13}},"selectionRange":{"start":{"line":297,"character":1},"end":{"line":297,"character":13}}},{"name":"EquipSlot","detail":"string","kind":8,"range":{"start":{"line":299,"character":1},"end":{"line":299,"character":24}},"selectionRange":{"start":{"line":299,"character":1},"end":{"line":299,"character":10}}}]},{"name":"(EquipableComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":302,"character":0},"end":{"line":304,"character":1}},"selectionRange":{"start":{"line":302,"character":28},"end":{"line":302,"character":41}}},{"name":"EquipPosition","detail":"string","kind":15,"range":{"start":{"line":306,"character":5},"end":{"line":306,"character":25}},"selectionRange":{"start":{"line":306,"character":5},"end":{"line":306,"character":18}}},{"name":"EquipHead","detail":"EquipPosition","kind":14,"range":{"start":{"line":308,"character":0},"end":{"line":314,"character":1}},"selectionRange":{"start":{"line":309,"character":1},"end":{"line":309,"character":10}}},{"name":"EquipShield","detail":"EquipPosition","kind":14,"range":{"start":{"line":308,"character":0},"end":{"line":314,"character":1}},"selectionRange":{"start":{"line":310,"character":1},"end":{"line":310,"character":12}}},{"name":"EquipWeapon","detail":"EquipPosition","kind":14,"range":{"start":{"line":308,"character":0},"end":{"line":314,"character":1}},"selectionRange":{"start":{"line":311,"character":1},"end":{"line":311,"character":12}}},{"name":"EquipBoots","detail":"EquipPosition","kind":14,"range":{"start":{"line":308,"character":0},"end":{"line":314,"character":1}},"selectionRange":{"start":{"line":312,"character":1},"end":{"line":312,"character":11}}},{"name":"EquipArmor","detail":"EquipPosition","kind":14,"range":{"start":{"line":308,"character":0},"end":{"line":314,"character":1}},"selectionRange":{"start":{"line":313,"character":1},"end":{"line":313,"character":11}}},{"name":"EquipmentPositions","detail":"[]EquipPosition","kind":13,"range":{"start":{"line":316,"character":0},"end":{"line":322,"character":1}},"selectionRange":{"start":{"line":316,"character":4},"end":{"line":316,"character":22}}},{"name":"EquipmentComponent","detail":"struct{...}","kind":23,"range":{"start":{"line":324,"character":5},"end":{"line":327,"character":1}},"selectionRange":{"start":{"line":324,"character":5},"end":{"line":324,"character":23}},"children":[{"name":"Base","detail":"struct{...}","kind":8,"range":{"start":{"line":325,"character":1},"end":{"line":325,"character":18}},"selectionRange":{"start":{"line":325,"character":1},"end":{"line":325,"character":5}}},{"name":"Items","detail":"map[EquipPosition]*ecs.Entity","kind":8,"range":{"start":{"line":326,"character":1},"end":{"line":326,"character":36}},"selectionRange":{"start":{"line":326,"character":1},"end":{"line":326,"character":6}}}]},{"name":"(*EquipmentComponent).UpdateStats","detail":"(player *ecs.Entity)","kind":6,"range":{"start":{"line":329,"character":0},"end":{"line":338,"character":1}},"selectionRange":{"start":{"line":329,"character":29},"end":{"line":329,"character":40}}},{"name":"(EquipmentComponent).OnAdd","detail":"(engine *ecs.Engine, entity *ecs.Entity)","kind":6,"range":{"start":{"line":340,"character":0},"end":{"line":343,"character":1}},"selectionRange":{"start":{"line":340,"character":28},"end":{"line":340,"character":33}}},{"name":"(EquipmentComponent).OnRemove","detail":"(engine *ecs.Engine, entity *ecs.Entity)","kind":6,"range":{"start":{"line":345,"character":0},"end":{"line":348,"character":1}},"selectionRange":{"start":{"line":345,"character":28},"end":{"line":345,"character":36}}},{"name":"(EquipmentComponent).ComponentType","detail":"()","kind":6,"range":{"start":{"line":350,"character":0},"end":{"line":352,"character":1}},"selectionRange":{"start":{"line":350,"character":28},"end":{"line":350,"character":41}}}]

```

**Comment by hyangah** [comment]
Thanks @jmaister !
I think this is https://github.com/golang/go/issues/46667
Good news is that gopls v0.7.1 is about to be released and there is a prerelease you can test with. 
Can you please verify if it's fixed in v0.7.1-pre.1? 

```
$ go install golang.org/x/tools/gopls@v0.7.1-pre.1
```

**Comment by jmaister** [comment]
After installing that version of gopls, still shows the error:

![imagen](https://user-images.githubusercontent.com/374021/127407191-685fd464-8050-4062-bb2f-4f49b45d8aa6.png)

**Comment by hyangah** [comment]
From the error message, they look like different errors - the error message shows that there is no module that has the `state` package. Is it indeed in a separate module?

**Comment by jmaister** [comment]
Yes, it's a separate module in a folder of the project.

**Comment by hyangah** [comment]
For multi-module workspace, please follow the instruction here 
https://github.com/golang/tools/blob/master/gopls/doc/workspace.md#multiple-modules

The easiest solution IMO is to enable the experimental workspace module feature 
https://github.com/golang/vscode-go/blob/master/docs/settings.md#buildexperimentalworkspacemodule

**Comment by jmaister** [comment]
After activating the option "experimentalWorkspaceModule", the errors keep showing.

```json
{
    "files.eol": "\n",
    "gopls": {
        "build.experimentalWorkspaceModule": true
    }
}
```

The project with no changes:
![imagen](https://user-images.githubusercontent.com/374021/127573274-3515b083-cce4-49de-a2ba-501dd032c0e7.png)

The problems tab when a cycle is introduced:
![imagen](https://user-images.githubusercontent.com/374021/127573423-d7e96734-4d6b-43e9-a422-a19e255f108b.png)

The problems tab when the cycle is removed:
![imagen](https://user-images.githubusercontent.com/374021/127573530-c4820764-48e1-4907-8fbc-bfce199e6903.png)

**Comment by findleyr** [comment]
Hi, this may be a dupe of https://golang.org/issue/46667. We can see if this is fixed by the upcoming gopls v0.7.1 release scheduled for Monday.

**Comment by hyangah** [comment]
gopls v0.7.1 was released. @jmaister can you please check if gopls v0.7.1 helped?

**Comment by jmaister** [comment]
Trying to create a new cycle, shows the cycle and the other affecting files:
![imagen](https://user-images.githubusercontent.com/374021/128726832-778764aa-b4f1-490b-99cd-be21aad56b3c.png)

Then after resolving it, stills shows the other files as error and it should not:
![imagen](https://user-images.githubusercontent.com/374021/128726981-24ad67e1-aa6b-43bb-b15e-8e7f794ee9a9.png)

**Comment by findleyr** [comment]
Hmm, thanks for reporting. I'll take a look.

**Comment by findleyr** [comment]
Just pinging this since it's been over three weeks: I haven't had a chance to investigate, but it is still in my queue. Sorry, will try to get to this in the next week.

**Comment by findleyr** [comment]
I believe this was fixed by https://go.dev/issue/52729, and should be fixed in the next gopls release.
