### ISSUE TITLE
Debugging goes into proc.go at every step

### ISSUE THREAD

**Issue by qidi1** [golang/vscode-go#1666]
I'm using go modules, and every debug step into or step over goes into a proc.go file gopark function and then goes back. You can see it in this gif. https://gyazo.com/adb4a54cc467ce372a4b5595b72d150f
launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Package",
            "type": "go",
            "request": "launch",
            "mode": "test",
            "program": "${workspaceRoot}/server/core",
            "args":[
                "-check.f",
                "TestBasic"
            ],
        }
    ]
}
```
it is same problem like this https://github.com/Microsoft/vscode-go/issues/2133,it said this bug is already fixed but i meet this again,my vscode vesion is 1.58.2.0.

**Comment by hyangah** [comment]
The fix isn't released yet. We mark an issue as fixed when the fix is merged. 
Release progress is in https://github.com/golang/vscode-go/issues/1659
In the mean time, try [the new debug adapter](https://github.com/golang/vscode-go/blob/v0.26.0/docs/dlv-dap.md) (by adding the property `"debugAdpater": "dlv-dap"` to the configuration) or try [the nightly extension](https://github.com/golang/vscode-go/blob/master/docs/nightly.md).

**Comment by mgabeler-lee-6rs** [comment]
The original issue was tagged as fixed by https://github.com/microsoft/vscode/issues/65920 which was closed as fixed in https://github.com/microsoft/vscode/commit/2a0a6ebad95e1483a81682e97d4ff91ae730edda on January 23rd, _2019_

**Comment by qidi1** [comment]
I lowered the vscode version to 1.57.1 ​​and the problem disappeared. I also tried vscode version 1.59.0 and the problem still exists. Maybe it's a problem with vscode,

**Comment by hyangah** [comment]
Go extension [v0.27.0](https://github.com/golang/vscode-go/releases/tag/v0.27.0) was just released. Please update the extension and see if it addressed the issue. Thanks!

**Comment by hyangah** [comment]
dlv-dap uses a different approach for data loading - it loads more on demand. For strings, it also uses a large limit for default. See https://github.com/golang/vscode-go/blob/master/docs/debugging.md#settings 
We hope `maxStringLen` is no longer necessary in most cases - if not, please let us know what limit you want to see. :-)

**Comment by hyangah** [comment]
Delve DAP which didn't have this issue is now the default debug adapter. Moreover @suzmue fixed the root cause of the legacy debug adapter too and the fix was released in v0.27.0. 
Closing.
