### ISSUE TITLE
vscode can't add break point for binary app run in docker with dlv-dap

### ISSUE THREAD

**Issue by poisson0106** [golang/vscode-go#2349]
Hi, I'm the new comer for the vscode go extension. It's a really excited extension I have used ever. But I met a little block in remote debug function. I have an built binary go application run in docker and has exposed 2345 with dlv. Here is the start command in docker:
`dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec ./webproj`
And the 2345 has indeed exposed when check with docker command
> CONTAINER ID   IMAGE          COMMAND                  CREATED             STATUS         PORTS                                            NAMES
be4996e5a77d   679b1fd4b28c   "/bin/bash ./build.sh"   About an hour ago   Up 8 minutes   0.0.0.0:2345->2345/tcp, 0.0.0.0:8080->8080/tcp   beego_proj
f0834dcbfe65   mysql          "docker-entrypoint.s…"   16 months ago       Up 2 hours     0.0.0.0:3306->3306/tcp, 33060/tcp                mysql-k8s

Also I use Goland to connect, **it connects successfully** and I can add breakpoint to function and it does work. 
But when I use the following launch.json to connect to the 2345 port:
`{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Delve into Docker",
            "type": "go",
            "debugAdapter": "dlv-dap",
            "request": "attach",
            "trace": "verbose",
            "mode": "remote",
            "cwd": "${workspaceFolder}",
            "showLog": true,
            "port": 2345,
            "host": "localhost",
            "substitutePath": [
                {
                    "from": "${workspaceFolder}",
                    "to": "/var/lib/www/"
                }
            ]
        }
    ]
}`

Yes it can be connected,  but when I add the break point, it break point is not red and show like **"could not find file /var/lib/www/controllers/usercontroller.go"**. But I have put the compiled file(named webproj) under /var/lib/www. Not quite sure why the extension tries to find source code in that folder, and I want to know how to attach to a complied single execution file. Since I take the guides https://github.com/golang/vscode-go/wiki/debugging#remote-debugging as reference. 

Thanks.

**Comment by hyangah** [comment]
was your binary built from **source code** located in the `/var/lib/www` directory? `substitutePath` is the hint `delve` uses to map the source code layout VSCode sees and the source code layout used when the binary was built.

**Comment by poisson0106** [comment]
> was your binary built from **source code** located in the `/var/lib/www` directory? `substitutePath` is the hint `delve` uses to map the source code layout VSCode sees and the source code layout used when the binary was built.

Do you mean the source code also should be copied to '/var/lib/www'? Current under '/var/lib/www', there is only binary file built with source code. And yes I check within the docker and the file existed. Using the GoLand also can connect to debug it.

**Comment by jamalc** [comment]
Does the issue happen for you in version 0.34.1 of the extension?

**Comment by lucasfreitas-dev** [comment]
Just a update, my problem was fixed by patch `0.35.1`

> I have the same `could not find file...` error on version `0.35.0`, on version `0.34.1` everything works fine here.

**Comment by poisson0106** [comment]
@jamalc Yes... I have updated version to 0.35.1 and it still existed. I attach my dockerfile in the following. Not quite sure if it will help to locate problem.
`FROM golang:1.16.15

RUN mkdir -p /var/lib/www && mkdir -p /var/lib/temp

WORKDIR /var/lib/temp
COPY . ./
RUN go env -w GOPROXY="https://goproxy.cn,direct"
RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go mod tidy
RUN go build
RUN mv ./webproj /var/lib/www/ && rm -rf /var/lib/temp

WORKDIR /var/lib/www

COPY ./build.sh ./

EXPOSE 8080
EXPOSE 2345

RUN chmod 777 ./webproj
RUN chmod 777 ./build.sh
# RUN dlv --listen=:2345 --headless=true --api-version=2 --accept-multiclient exec ./webproj
ENTRYPOINT ["/bin/bash","./build.sh"]
# ENTRYPOINT ["./webproj"]`

And I use Goland to run the docker file.

![pic1](https://user-images.githubusercontent.com/3365321/180006438-93b40da4-685b-4ae0-9ab8-d10663fddf7c.jpg)

When I use the goland to connect. It does work. Like following
![pic2](https://user-images.githubusercontent.com/3365321/180006713-8228771c-1bad-4da1-9c1b-df851b994338.jpg)

But when I use the vscode, it can not add as a valid break point. Please check.
<img width="760" alt="pic3" src="https://user-images.githubusercontent.com/3365321/180007231-cca7e43a-7f04-40a2-8d50-976412b25014.png">

**Comment by hyangah** [comment]
The binary was compiled from `/var/lib/temp` so I guess substitute path should look like 

` "from": "${workspaceFolder}", "to": "/var/lib/temp"`

**Comment by poisson0106** [comment]
> The binary was compiled from `/var/lib/temp` so I guess substitute path should look like
> 
> ` "from": "${workspaceFolder}", "to": "/var/lib/temp"`

@hyangah ， it does work!  But I'm not clear, the source code and related folder(/var/lib/temp) in docker has been deleted in docker build. Why should substitute path point to a deleted path and it will work? In my former comprehension, it should point to a existed file(binary file or source path in docker). Would you give some message about the reason? 

Anyway, thanks a lot!

**Comment by hyangah** [comment]
Delve uses the source file location embedded inside the built executable. The info is determined when the executable is built. Even when you move the executable to other directory or even to a different machine, the info doesn't change.

Then during the debug session, Delve tries to map the source code paths the editor sees  and the file location paths embedded in the executable. `substitutePath` gives hints for this mapping. 

Glad to hear that your problem went away. Closing this.
