### ISSUE TITLE
Feature Request: Go Templates Support

### ISSUE THREAD

**Issue by timkofu** [golang/vscode-go#609]
Would it be possible to add formatting, autocomplete, and colorization for Go templates? (.tmpl)

**Comment by hyangah** [comment]
The prior discussion history is here https://github.com/microsoft/vscode-go/issues/228

We hope `gopls` can support formatting and autocompletion (https://github.com/golang/go/issues/36911)

How to provide syntax highlighting based on [textmate](https://github.com/jeff-hykin/better-go-syntax) or [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) provided through LSP future release - that still need to be figured out.

/cc @stamblerre

**Comment by stamblerre** [comment]
> How to provide syntax highlighting based on [textmate](https://github.com/jeff-hykin/better-go-syntax) or [semantic highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) provided through LSP future release - that still need to be figured out.

I wonder if we could do this through LSP's upcoming semantic tokens feature: https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/#textDocument_semanticTokens.

**Comment by stamblerre** [comment]
@hyangah: Should this be in the `gopls` on by default project? It seems to me like this isn't necessary to turn on `gopls` by default.

**Comment by inliquid** [comment]
Any reason why `*.tmpl` extension is chosen? Most of the time I saw either `*.gohtml` or just `*.html` when Go templates used on web. And when working with `html` templates one would want both HTML and Go language features be present in editor at the same time, otherwise you'd have to manually switch language back and forth.

**Comment by stamblerre** [comment]
We are adding incremental support for templates, starting with files with the `.tmpl` extension (https://golang.org/cl/297871). In the future, we will expand this to include other file extensions and to include templates within strings in Go files.

**Comment by inliquid** [comment]
Any way to make `vscode-go` understand other extensions at an early stage? I'm building html templates and I can test how new features work in real life, but in order to do so, if I understand correctly, I would have to rename all templates to have `*.tmpl`? That would be not very convenient.

**Comment by oliverpool** [comment]
@inliquid in vscode, you can `Change language mode` (from the command palette). You can adjust for a specific file or for all files matching the current extension (I think there is also a JSON settings for this).

**Comment by inliquid** [comment]
@oliverpool I'm aware of this option, but not sure how it helps. Generally I would like to have support of go templates when working on `*.html` files with HTML language features enabled by default. Switching from HTML language to templates back and forth is far from good user experience. 

Example: please see how it's done in Goland.

**Comment by oliverpool** [comment]
Sorry, I only replied to this part of your comment:
> I would have to rename all templates to have `*.tmpl`

I agree with you that the supporting a mix of HTML and go template would greatly improve the developer experience (I am using [`esbenp.prettier-vscode`](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) with https://www.npmjs.com/package/prettier-plugin-go-template for now)

**Comment by IanVS** [comment]
It looks like the referenced https://github.com/golang/go/issues/36911 has been closed, does that mean template highlighting should work now?  Sorry, I'm new to working with golang, and just trying to figure out how to get syntax highlighting in my html go templates.  Whether that means using a specific naming convention or enabling a setting...

**Comment by hyangah** [comment]
gopls [v0.7.5](https://github.com/golang/tools/releases/tag/gopls%2Fv0.7.5) has template support for files with language id `gotmpl`. (Go Template File)

VSCode Go extension v0.31.0 will classify files with extension `*.tmpl` or `*.gotmpl` as the `gotmpl` language file by default. You can override the default by eithre using
  - the ["Select Language Mode" dropdown](https://code.visualstudio.com/docs/languages/overview#_changing-the-language-for-the-selected-file), or
  - by configuring `files.associations` settings:
  ```
           "files.associations": {
               "*.tmpl": "plaintext",
               "*.mycoolgotemplate": "gotmpl"
           }
  ```        

We are very close to v0.31.0 - RC1 is available for testing at https://github.com/golang/vscode-go/releases/tag/v0.31.0-rc.1

Supported features are
  - syntax highlighting (when used in combination with`"gopls": { "ui.semanticTokens": true }`)
  - some autocompletion
  - diagnostics (if you want the diagnostics on all files, not only open files, consider setting `"gopls" : { "build.templateExtensions": true }` in your settings.json.

Templates embedded in .go file, diagnostics beyond the template file itself (e.g. detecting runtime error such as validation of data, associated templates, custom functions, ...) are not in the scope of supported features. 

cc @pjweinb @findleyr

**Comment by pd93** [comment]
Just curious on how this work is going? I've been messing around with the HTML templating support for Go and have found that I still can't quite get it to work how I want.

Given the following basic HTML template:
```html
<!-- test.html -->
<!DOCTYPE html>
    <head>
    </head>
    <body>
        <div>
            {{ .SomeVal }}
        </div>
    </body>
</html>
```

and the following `settings.json` file:
```jsonc
// .vscode/settings.json
{
    "editor.formatOnSave": true,
}
```

upon saving the file, the default HTML formatter runs and works as expected. It even deals with `{{ x }}` correctly. (Also works for  any other template syntax I can throw at it):

![image](https://user-images.githubusercontent.com/9294862/158594024-4431f27a-d8c3-462f-960a-5aab54409372.png)

However, once I change my settings as per the [documentation](https://github.com/golang/tools/blob/master/gopls/doc/features.md#template-files):
```json
{
    "editor.formatOnSave": true,
    "files.associations": {
        "*.html": "gotmpl"
    },
    "gopls": {
        "build.templateExtensions": [
            ".html"
        ],
    },
}
```

This happens:

![image](https://user-images.githubusercontent.com/9294862/158594981-bbf85910-8dea-4d7e-8353-b487ca72554d.png)

Syntax highlighting for the templating handlebars works as expected, but not for the HTML. Also, because its not considered to be an HTML file, none of the formatters run. This also applies to other embedded languages like JS:

![image](https://user-images.githubusercontent.com/9294862/158595631-b66e67b1-1c0d-44a6-aa41-edac5d0780da.png)

At the moment I'm stuck not using the go templating features because of this. Usually, I would just accept this and continue to use a regular HTML formatter as it works with most templating features. However, the default VSCode beautifier has its own issues when it comes to formatting template handlebars in embedded Javascript:

![image](https://user-images.githubusercontent.com/9294862/158597438-7eb79cdb-8769-4098-abee-ee4f63c4778a.png)

I'd be grateful if you're able to share any existing solutions to any of the above and if not, whether these are known problems and whether they are on the roadmap. Thanks! :)

**Comment by hyangah** [comment]
In VSCode, I toggle between languages using the language tab at the bottom of the window rather than the settings.json.
https://github.com/golang/vscode-go/blob/master/docs/features.md#go-template-syntax-highlighting

**Comment by frederikhors** [comment]
I do not know if this can help but I'm using successfully this VSCode extension: https://github.com/jinliming2/vscode-go-template.

I had a problem today: https://github.com/jinliming2/vscode-go-template/issues/16.

**Comment by lehuuthoct** [comment]
Another approach with `Prettier` & `Emmet`
```json
"files.associations": {
    "*.tmpl": "html"
  },
```
`cmd + shift + p`: change language mode -> configure 

<img width="289" alt="image" src="https://user-images.githubusercontent.com/9996518/224861796-97d6f1d9-c046-41d4-8f20-b08405b58003.png">
<img width="287" alt="image" src="https://user-images.githubusercontent.com/9996518/224861830-a3868a64-fbbd-44f6-aa51-a85be1d3f43f.png">

`cmd+ alt + f`: It will be like this 
<img width="577" alt="image" src="https://user-images.githubusercontent.com/9996518/224861875-48105d6b-fbd5-4936-99e7-649a087425d9.png">

**Comment by tmc** [comment]
Since this is some support for this in gopls now, can this be worked on (or documented, if it's just a matter of documentation?) https://github.com/golang/tools/blob/master/gopls/doc/features.md#template-files

**Comment by hyangah** [comment]
That's already documented.
https://github.com/golang/vscode-go/wiki/features#go-template-syntax-highlighting
(commented in https://github.com/golang/vscode-go/issues/609#issuecomment-1072608480)

It is under syntax highlighting, but some completion or simple diagnostics are offered. 

The only reason we left this issue open was some users wanted to see the go template support coexist along with other languages (for example html? in https://github.com/golang/vscode-go/issues/609#issuecomment-1069119156), outlined in https://code.visualstudio.com/api/language-extensions/embedded-languages#language-services or ideas discussed in https://github.com/microsoft/vscode/issues/1751. But none of them seem like a trivial project.

Will close this issue since we don't have a plan to work on this. If a new easy way to handle this universal language injection from the extension side, please let us know by opening a new issue with the details.

Thanks.

**Comment by tmc** [comment]
It doesn't seem like the state of integration supports intelligent autocomplete, I think another issue to improve the quality of completions in templates would be appropriate.

**Comment by mortenson** [comment]
I just published a vscode plugin for go templates that supports autocomplete, to some degree, by transpiling go templates to go: https://github.com/mortenson/go-template-transpiler-extension

**Comment by ewh0** [comment]
checking back again in 2024... any update on this feature?

**Comment by quinn** [comment]
I don't get any sort of highlighting for go template tags when the language is selected:

![image](https://github.com/user-attachments/assets/c65acdcb-4895-4ae9-8477-bc47dbfb9106)

Is this expected?
